### ISSUE TITLE
ofd.js开源方案有缺陷

### ISSUE THREAD

**Issue by haozekang** [densen2014/BootstrapBlazor.OfdReader#1]
部分ofd无法正常打开、布局也会错乱

**Comment by densen2014** [comment]
谢谢反馈，请问有更合适的方案吗？可以来个pr

**Comment by haozekang** [comment]
> 谢谢反馈，请问有更合适的方案吗？可以来个pr

我也么有。。。

**Comment by densen2014** [comment]
> > 谢谢反馈，请问有更合适的方案吗？可以来个pr
> 
> 
> 
> 我也么有。。。

那咱就先按兵不动
